#!/bin/bash
# Builds Earwig and packages it as Earwig.app (required so macOS can grant
# microphone / system-audio / speech-recognition permissions to the app).
set -euo pipefail
cd "$(dirname "$0")"

CONFIG="${1:-release}"

# The macOS 27 SDK that Command Line Tools 26.x ships turns SwiftUI's @State
# into a macro whose plugin the bare tools don't carry ("plugin for module
# 'SwiftUIMacros' not found"). Build against the newest SDK below 27 unless
# the caller has chosen one. Remove once the tools ship the plugin, or when
# building under a full Xcode.
if [[ -z "${SDKROOT:-}" ]]; then
    SDKS="$(xcrun --show-sdk-path 2>/dev/null | sed 's#/MacOSX[^/]*\.sdk$##')"
    if [[ -n "$SDKS" ]]; then
        CANDIDATE="$(ls -d "$SDKS"/MacOSX26.[0-9]*.sdk 2>/dev/null | sort -V | tail -1)"
        if [[ -n "$CANDIDATE" ]]; then
            export SDKROOT="$CANDIDATE"
            echo "Building against $(basename "$SDKROOT")"
        fi
    fi
fi

swift build -c "$CONFIG" --product Earwig

BIN=".build/$CONFIG/Earwig"
APP="Earwig.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/Earwig"
# Icons are generated by assets/make-icons.swift (re-run it after editing).
cp assets/AppIcon.icns assets/MenuBarIcon.png assets/MenuBarIcon@2x.png "$APP/Contents/Resources/"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key><string>Earwig</string>
    <key>CFBundleIdentifier</key><string>io.darkin.earwig</string>
    <key>CFBundleName</key><string>Earwig</string>
    <key>CFBundleDisplayName</key><string>Earwig</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <key>CFBundleVersion</key><string>0.1.0</string>
    <key>CFBundleShortVersionString</key><string>0.1.0</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>LSMinimumSystemVersion</key><string>15.0</string>
    <key>LSUIElement</key><true/>
    <key>NSMicrophoneUsageDescription</key>
    <string>Earwig records your side of meetings so it can transcribe them.</string>
    <key>NSSpeechRecognitionUsageDescription</key>
    <string>Earwig transcribes recorded meetings on-device.</string>
    <key>NSAudioCaptureUsageDescription</key>
    <string>Earwig records meeting audio (the other participants) so it can transcribe the conversation.</string>
    <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# Prefer the stable local signing identity so TCC permission grants survive
# rebuilds; fall back to ad-hoc if it doesn't exist on this machine.
IDENTITY="Earwig Dev Signing"
if security find-identity -v -p codesigning 2>/dev/null | grep -q "$IDENTITY"; then
    codesign --force --sign "$IDENTITY" "$APP"
    echo "Signed with $IDENTITY"
else
    codesign --force --sign - "$APP"
    echo "Signed ad-hoc ($IDENTITY identity not found)"
fi
echo "Built $APP"
