import AppKit
import SwiftUI

/// The Summary settings tab: choose the engine (Ollama or Apple Intelligence), set it up
/// (install/pull for Ollama, availability for Apple), and configure auto-summarise + template +
/// custom instructions. Summaries are optional — transcription works without any of this.
///
/// All fields self-persist (engine/model on selection; toggle/template immediately; custom
/// instructions debounced) so the panel works the same in Settings and in onboarding.
struct SummarySettingsView: View {
    @Bindable var store: SettingsStore
    @State private var ollama: OllamaState
    @State private var saveTask: Task<Void, Never>?

    /// `ollama` can be injected so onboarding shares one instance between this panel and its
    /// "Finish" gate (which needs the model's install status). Settings just uses its own.
    @MainActor
    init(store: SettingsStore, ollama: OllamaState? = nil) {
        _store = Bindable(wrappedValue: store)
        _ollama = State(initialValue: ollama ?? OllamaState())
    }

    @State private var claudeKey = SecretStore.anthropicKey ?? ""
    @State private var keySaved = false
    @State private var keySavedResetTask: Task<Void, Never>?
    @State private var testingClaude = false

    private var engine: SummaryEngineKind { SummaryEngineKind.from(store.config.summaryEngine) }

    /// The chosen Ollama model tag. Empty config and superseded legacy tags both resolve to the
    /// current recommended model, so an existing install on the old weak default shows the new one.
    private var modelTag: String {
        SummaryModels.resolved(override: store.config.summaryModelID).id
    }

    var body: some View {
        VStack(alignment: .leading, spacing: Spacing.xl) {
            engineSection
            Hairline()
            switch engine {
            case .ollama: ollamaSection
            case .apple: appleSection
            case .claude: claudeSection
            }
            Hairline()
            optionsSection
        }
        .task { await ollama.refresh() }
        .onChange(of: store.config.autoSummarize) { _, _ in store.save() }
        .onChange(of: store.config.summaryTemplateID) { _, _ in store.save() }
        .onChange(of: store.config.customSummaryInstructions) { _, _ in debouncedSave() }
        .onChange(of: store.config.summaryClaudeModel) { _, _ in store.save() }
    }

    // MARK: - Engine picker

    private var engineSection: some View {
        FlatSection("Summary engine") {
            Text("Summaries are generated by the engine you select here.")
                .font(.captionText).foregroundStyle(Theme.textTertiary)
            VStack(spacing: Spacing.sm) {
                ForEach(SummaryEngineKind.allCases) { engineRow($0) }
            }
        }
    }

    private func engineRow(_ kind: SummaryEngineKind) -> some View {
        let selected = engine == kind
        return Button {
            store.config.summaryEngine = kind.rawValue
            store.save()
        } label: {
            HStack(alignment: .center, spacing: Spacing.md) {
                RoundedRectangle(cornerRadius: Radius.control, style: .continuous)
                    .fill(kind.brandGradient)
                    .frame(width: 40, height: 40)
                    .overlay(
                        Image(systemName: kind.icon)
                            .font(.system(size: 17, weight: .semibold))
                            .foregroundStyle(.white))
                    .shadow(color: .black.opacity(0.12), radius: 4, y: 2)
                VStack(alignment: .leading, spacing: Spacing.xxs) {
                    HStack(spacing: Spacing.sm) {
                        Text(kind.displayName).font(.rowTitle).foregroundStyle(Theme.textPrimary)
                        if selected { Badge(text: "Active", style: .dot) }
                    }
                    Text(kind.blurb).font(.captionText).foregroundStyle(Theme.textSecondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
                Spacer(minLength: Spacing.sm)
                Image(systemName: selected ? "checkmark.circle.fill" : "circle")
                    .font(.title3)
                    .foregroundStyle(selected ? Theme.accent : Theme.textTertiary)
            }
            .padding(Spacing.md)
            .background(
                RoundedRectangle(cornerRadius: Radius.control, style: .continuous)
                    .fill(selected ? Theme.elevated : Color.clear))
            .overlay(
                RoundedRectangle(cornerRadius: Radius.control, style: .continuous)
                    .stroke(selected ? Theme.accent.opacity(0.5) : Theme.hairline, lineWidth: 1))
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain).clickableCursor()
        .accessibilityLabel("\(kind.displayName)\(selected ? ", active" : "")")
        .accessibilityAddTraits(selected ? [.isButton, .isSelected] : .isButton)
    }

    // MARK: - Apple Intelligence

    @ViewBuilder
    private var appleSection: some View {
        FlatSection("Apple Intelligence") {
            switch AppleSummaryEngine.availability() {
            case .ready:
                statusRow(ok: true, "Ready. Apple's on-device model is available. No download needed.")
            case .needsSetup(let reason):
                statusRow(ok: false, reason)
            }
        }
    }

    // MARK: - Claude

    @ViewBuilder
    private var claudeSection: some View {
        FlatSection("Claude") {
            VStack(alignment: .leading, spacing: Spacing.lg) {
                VStack(alignment: .leading, spacing: Spacing.sm) {
                    HStack(spacing: Spacing.sm) {
                        SecureField("Anthropic API key (sk-ant-\u{2026})", text: $claudeKey)
                            .textFieldStyle(.roundedBorder)
                        Button {
                            SecretStore.anthropicKey = claudeKey
                            ToastCenter.shared.success(claudeKey.isEmpty ? "API key cleared" : "API key saved")
                            keySaved = true
                            keySavedResetTask?.cancel()
                            keySavedResetTask = Task {
                                try? await Task.sleep(for: .seconds(1.6))
                                guard !Task.isCancelled else { return }
                                keySaved = false
                            }
                        } label: {
                            if keySaved {
                                Label("Saved", systemImage: "checkmark")
                            } else {
                                Text("Save key")
                            }
                        }
                        .buttonStyle(SecondaryButtonStyle())
                        .animation(.smooth(duration: 0.2), value: keySaved)
                    }
                    if claudeKey.isEmpty {
                        Text("Add your Anthropic API key above to use Claude for summaries.")
                            .font(.captionText).foregroundStyle(Theme.amber)
                    }
                    Button {
                        testClaudeConnection()
                    } label: {
                        if testingClaude {
                            HStack(spacing: Spacing.xs) {
                                ProgressView().controlSize(.small)
                                Text("Testing…")
                            }
                        } else {
                            Label("Test connection", systemImage: "bolt.horizontal")
                        }
                    }
                    .buttonStyle(SecondaryButtonStyle())
                    .disabled(claudeKey.isEmpty || testingClaude)
                }
                FieldRow("Model") {
                    GlossyMenu(
                        selection: $store.config.summaryClaudeModel,
                        options: [
                            ("claude-sonnet-4-6", "Claude Sonnet 4.6"),
                            ("claude-opus-4-8", "Claude Opus 4.8"),
                            ("claude-haiku-4-5-20251001", "Claude Haiku 4.5"),
                        ],
                        systemImage: "cpu")
                }
                Label("This sends your transcript text to Anthropic when you summarise or Ask.", systemImage: "exclamationmark.triangle.fill")
                    .foregroundStyle(Theme.amber)
                    .font(.captionText)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }

    // MARK: - Ollama

    @ViewBuilder
    private var ollamaSection: some View {
        FlatSection("Ollama") {
            switch ollama.reach {
            case .unknown:
                ProgressView().controlSize(.small)
            case .unreachable:
                ollamaNotRunning
            case .reachable:
                infoText("Pick a model. Bigger models write richer summaries but use more disk and memory. You can run any model you've pulled.")
                VStack(alignment: .leading, spacing: Spacing.lg) {
                    ForEach(Array(modelRows.enumerated()), id: \.element.id) { index, model in
                        if index > 0 { Hairline() }
                        modelRow(model)
                    }
                }
            }
        }
    }

    private var ollamaNotRunning: some View {
        VStack(alignment: .leading, spacing: Spacing.md) {
            statusRow(ok: false, "Ollama isn't running. Install it (or open the Ollama app), then check again.")
            HStack(spacing: Spacing.sm) {
                Button("Get Ollama") {
                    NSWorkspace.shared.open(URL(string: "https://ollama.com/download")!)
                }
                .buttonStyle(PrimaryButtonStyle())
                Button("Check again") { Task { await ollama.refresh() } }
                    .buttonStyle(SecondaryButtonStyle())
            }
        }
    }

    /// Catalog models plus any installed model not already in the catalog.
    private var modelRows: [SummaryModels.Model] {
        let extra = ollama.installed
            .map(\.name)
            .filter { tag in !SummaryModels.catalog.contains { $0.id == tag } }
            .map { SummaryModels.resolved(override: $0) }
        return SummaryModels.catalog + extra
    }

    private func modelRow(_ model: SummaryModels.Model) -> some View {
        let isDefault = model.id == modelTag
        let installed = ollama.isInstalled(model.id)
        return HStack(alignment: .top, spacing: Spacing.md) {
            Button { setDefault(model) } label: {
                Image(systemName: isDefault ? "largecircle.fill.circle" : "circle")
                    .foregroundStyle(isDefault ? Theme.accent : Theme.textTertiary)
            }
            .buttonStyle(.plain).clickableCursor()
            .accessibilityLabel(isDefault ? "\(model.name), default" : "Set \(model.name) as default")

            VStack(alignment: .leading, spacing: Spacing.xxs) {
                HStack(spacing: Spacing.sm) {
                    Text(model.name).font(.rowTitle).foregroundStyle(Theme.textPrimary)
                    if isDefault { Badge(text: "default", style: .dot) }
                }
                Text(model.blurb).font(.captionText).foregroundStyle(Theme.textSecondary)
                if isDefault, !installed, ollama.pull(for: model.id) == nil {
                    Text("Not installed yet. Download it below to summarise with it.")
                        .font(.captionText).foregroundStyle(Theme.amber)
                }
            }
            Spacer(minLength: Spacing.sm)
            action(for: model, installed: installed)
        }
    }

    @ViewBuilder
    private func action(for model: SummaryModels.Model, installed: Bool) -> some View {
        switch ollama.pull(for: model.id) {
        case .pulling(let f):
            VStack(alignment: .trailing, spacing: Spacing.xs) {
                ProgressView(value: f).tint(Theme.accent).frame(width: 90)
                Text(f, format: .percent.precision(.fractionLength(0)))
                    .font(.captionText).monospacedDigit().foregroundStyle(Theme.textSecondary)
            }
        case .failed(let detail):
            VStack(alignment: .trailing, spacing: Spacing.xs) {
                Text("Failed").font(.captionText).foregroundStyle(Theme.danger)
                Button("Retry") { ollama.pullModel(model.id) }
                    .buttonStyle(SecondaryButtonStyle())
            }
            .help(detail)
        case nil:
            if installed {
                Label("Installed", systemImage: "checkmark")
                    .font(.captionText).foregroundStyle(Theme.textSecondary)
                    .labelStyle(.titleAndIcon)
            } else {
                Button("Download") { ollama.pullModel(model.id) }
                    .buttonStyle(SecondaryButtonStyle())
                    .help(model.approxSizeGB > 0 ? "~\(String(format: "%.1f", model.approxSizeGB)) GB" : "")
            }
        }
    }

    /// Save the entered key, then make a tiny Claude call to confirm the key + connectivity work.
    private func testClaudeConnection() {
        SecretStore.anthropicKey = claudeKey
        guard !claudeKey.isEmpty else {
            ToastCenter.shared.warning("Add a key first")
            return
        }
        testingClaude = true
        Task {
            do {
                _ = try await ClaudeClient(model: store.config.summaryClaudeModel, maxTokens: 16)
                    .complete(system: "Reply with the single word OK.", prompt: "Connection test.")
                ToastCenter.shared.success("Claude connected")
            } catch {
                ToastCenter.shared.error((error as? LocalizedError)?.errorDescription ?? "Connection failed")
            }
            testingClaude = false
        }
    }

    private func setDefault(_ model: SummaryModels.Model) {
        store.config.summaryModelID = model.id
        store.save()
    }

    // MARK: - Options (shared)

    private var optionsSection: some View {
        FlatSection("Summaries") {
            Toggle("Summarise automatically after each meeting", isOn: $store.config.autoSummarize)
                .tint(Theme.accent)
                .font(.bodyText)
            FieldRow("Template") {
                GlossyMenu(
                    selection: $store.config.summaryTemplateID,
                    options: SummaryTemplate.builtIns.map { ($0.id, $0.name) },
                    systemImage: "doc.text")
            }
            caption(SummaryTemplate.byID(store.config.summaryTemplateID).instructions)
            VStack(alignment: .leading, spacing: Spacing.xs) {
                Text("Custom instructions").font(.label).foregroundStyle(Theme.textPrimary)
                TextEditor(text: $store.config.customSummaryInstructions)
                    .font(.bodyText).frame(height: 80)
                    .scrollContentBackground(.hidden)
                    .padding(Spacing.sm)
                    .background(RoundedRectangle(cornerRadius: Radius.control, style: .continuous).fill(Theme.surface))
                    .overlay(RoundedRectangle(cornerRadius: Radius.control, style: .continuous).stroke(Theme.hairline, lineWidth: 1))
                caption("Optional. Overrides the template's built-in guidance.")
            }
        }
    }

    // MARK: - Persistence

    /// Debounce custom-instruction saves so we don't write on every keystroke.
    private func debouncedSave() {
        saveTask?.cancel()
        saveTask = Task {
            try? await Task.sleep(for: .seconds(0.6))
            guard !Task.isCancelled else { return }
            store.save()
        }
    }

    // MARK: - Building blocks

    private func statusRow(ok: Bool, _ text: String) -> some View {
        HStack(alignment: .top, spacing: Spacing.sm) {
            Image(systemName: ok ? "checkmark.circle.fill" : "exclamationmark.triangle.fill")
                .foregroundStyle(ok ? Theme.accent : Theme.amber)
            Text(text).font(.bodyText).foregroundStyle(Theme.textSecondary)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    private func infoText(_ markdown: String) -> some View {
        Text(.init(markdown)).font(.bodyText).foregroundStyle(Theme.textSecondary)
            .fixedSize(horizontal: false, vertical: true)
    }

    private func caption(_ text: String) -> some View {
        Text(text).font(.captionText).foregroundStyle(Theme.textTertiary)
            .frame(maxWidth: .infinity, alignment: .leading)
    }
}
