import SwiftUI

/// The Summary tab: the LLM's TL;DR, key points, and decisions, plus a template picker and
/// Regenerate control. Shows a friendly empty state for meetings that haven't been
/// summarized yet (e.g. recorded before summaries existed), and a spinner while generating.
struct SummaryView: View {
    let stored: StoredSummary?
    let isSummarizing: Bool
    let errorMessage: String?
    var speakerNames: [String] = []
    @Binding var templateID: String
    let onGenerate: () -> Void
    let onCopy: () -> Void

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: Spacing.lg) {
                controls
                if isSummarizing {
                    generating
                } else {
                    // Surface a failure even when an earlier summary is still on screen, so a
                    // failed regenerate doesn't silently show stale content.
                    if let errorMessage { failureState(errorMessage) }
                    if let stored {
                        body(for: stored)
                    } else if errorMessage == nil {
                        emptyState
                    }
                }
            }
            .padding(Spacing.xl)
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    private func failureState(_ message: String) -> some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            Label("Couldn't generate a summary", systemImage: "exclamationmark.triangle.fill")
                .font(.rowTitle).foregroundStyle(Theme.amber)
            Text(message)
                .font(.bodyText).foregroundStyle(Theme.textSecondary)
                .fixedSize(horizontal: false, vertical: true)
            Button("Try again", action: onGenerate)
                .buttonStyle(PrimaryButtonStyle())
                .padding(.top, Spacing.xs)
        }
        .padding(.top, Spacing.sm)
    }

    private var controls: some View {
        HStack(spacing: Spacing.md) {
            GlossyMenu(
                selection: $templateID,
                options: SummaryTemplate.builtIns.map { ($0.id, $0.name) },
                systemImage: "doc.text")
            Button(stored == nil ? "Generate" : "Regenerate", action: onGenerate)
                .buttonStyle(PrimaryButtonStyle(size: .compact))
                .disabled(isSummarizing)
            Spacer()
            if stored != nil {
                Button("Copy", systemImage: "doc.on.doc", action: onCopy)
                    .buttonStyle(SecondaryButtonStyle())
                    .disabled(isSummarizing)
            }
        }
    }

    private var generating: some View {
        HStack(spacing: Spacing.sm) {
            ProgressView().controlSize(.small).tint(Theme.accent)
            Text("Summarising on-device…").font(.bodyText).foregroundStyle(Theme.textSecondary)
        }
        .padding(.vertical, Spacing.sm)
    }

    private var emptyState: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            Image(systemName: "sparkles").font(.largeTitle).foregroundStyle(Theme.textTertiary)
            Text("No summary yet").font(.rowTitle).foregroundStyle(Theme.textPrimary)
            Text("Generate an on-device summary of this meeting. Pick a template above, then press Generate.")
                .font(.bodyText).foregroundStyle(Theme.textSecondary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(.top, Spacing.sm)
    }

    private func body(for stored: StoredSummary) -> some View {
        let s = stored.summary
        return VStack(alignment: .leading, spacing: Spacing.xxl) {
            Text(NameHighlight.attributed(s.tldr, names: speakerNames))
                .font(.system(size: 17))
                .foregroundStyle(Theme.textPrimary)
                .lineSpacing(6)
                .textSelection(.enabled)
                .fixedSize(horizontal: false, vertical: true)

            if !s.keyPoints.isEmpty {
                bulletSection("Key points", s.keyPoints)
            }
            if !s.decisions.isEmpty {
                bulletSection("Decisions", s.decisions)
            }
            Text("Generated by \(stored.model) · \(SummaryTemplate.byID(stored.templateID).name)")
                .font(.captionText).foregroundStyle(Theme.textTertiary)
        }
    }

    private func bulletSection(_ title: String, _ items: [String]) -> some View {
        VStack(alignment: .leading, spacing: Spacing.lg) {
            SectionHeader(title)
            ForEach(Array(items.enumerated()), id: \.offset) { _, item in
                HStack(alignment: .top, spacing: Spacing.md) {
                    Circle().fill(Theme.accent.opacity(0.6)).frame(width: 5, height: 5).padding(.top, 8)
                    Text(NameHighlight.attributed(item, names: speakerNames))
                        .font(.bodyText).foregroundStyle(Theme.textPrimary)
                        .lineSpacing(5)
                        .textSelection(.enabled)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
    }
}
